#!/bin/bash

RED="\u001b[31m"
GREEN="\u001b[32m"
YELLOW="\u001b[33m"
BLUE="\u001b[34m"
MAGENTA="\u001b[35m"
CYAN="\u001b[36m"
ESC="\u001b[0m"

echo -e "$BLUE::$ESC This script is designed to run on$BLUE Arch Linux! $ESC"
echo -e "$BLUE::$ESC The directory $YELLOW$HOME/dotfiles$ESC$RED does not exist. $ESC"
echo -e "$BLUE::$ESC Debloating archinstall"
echo -e "$BLUE::$ESC Setting up pacman"
echo -e "$BLUE::$ESC YAY is installed"
echo -e "$BLUE::$ESC Installing YAY..."
echo -e "$BLUE::$ESC Rating mirrors"
echo -e "$BLUE::$ESC Installing packages"
echo -e "$BLUE::$ESC Installing themes"
echo -e "$BLUE::$ESC Checking for existing folders"
echo -e "$BLUE::$ESC Creating links"
echo -e "$BLUE::$ESC Setting up sensors"
echo -e "$BLUE::$ESC Creating user directories"
echo -e "$BLUE::$ESC Setting up asusctl"
echo -e "$BLUE::$ESC Setting up rust"
echo -e "$BLUE::$ESC Setting up nemo"
echo -e "$BLUE::$ESC Setting up timeshift"
echo -e "$BLUE::$ESC Setting up fish"
echo -e "$BLUE::$ESC Setting up power key"
echo -e "$BLUE::$ESC Setting up firewall"
echo -e "$BLUE::$ESC Setting up bun"
echo -e "$BLUE::$ESC Setting up electron"
echo -e "$BLUE::$ESC Setting up services"
echo -e "$BLUE::$ESC Finishing installation"
